
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action SaveDataAction;

	private global::Gtk.Action ExitProgramAction;

	private global::Gtk.Action ConnectToDeviceAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.DrawingArea drawingarea1;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entrySUbjID;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label3;

	private global::Gtk.Entry entryScanName;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment5;

	private global::Gtk.TextView textview1;

	private global::Gtk.Label GtkLabel9;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label7;

	private global::Gtk.ComboBox combobox5;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Entry entrywindowTime;

	private global::Gtk.CheckButton checkbuttonWIndowTime;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button buttonMarkStim;

	private global::Gtk.Label labelEvents;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.Label GtkLabel5;

	private global::Gtk.Frame frame7;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Button buttonStart;

	private global::Gtk.ProgressBar progressbar1;

	private global::Gtk.Frame frame9;

	private global::Gtk.Alignment GtkAlignment4;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label9;

	private global::Gtk.SpinButton spinbutton1;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Label label11;

	private global::Gtk.SpinButton spinbutton3;

	private global::Gtk.Label GtkLabel7;

	private global::Gtk.Label GtkLabel8;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label StatusBarLabel1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.Label StatusBarLabel2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.SaveDataAction = new global::Gtk.Action("SaveDataAction", global::Mono.Unix.Catalog.GetString("Save Data"), null, null);
		this.SaveDataAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save Data");
		w1.Add(this.SaveDataAction, null);
		this.ExitProgramAction = new global::Gtk.Action("ExitProgramAction", global::Mono.Unix.Catalog.GetString("Exit Program"), null, null);
		this.ExitProgramAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit Program");
		w1.Add(this.ExitProgramAction, null);
		this.ConnectToDeviceAction = new global::Gtk.Action("ConnectToDeviceAction", global::Mono.Unix.Catalog.GetString("Connect to Device"), null, null);
		this.ConnectToDeviceAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Connect to Device");
		w1.Add(this.ConnectToDeviceAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("No-FRAIL NIRS Muscle App");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ConnectToDeviceAction' action='ConnectToDeviceAction'/><menuitem name='SaveDataAction' action='SaveDataAction'/><menuitem name='ExitProgramAction' action='ExitProgramAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea();
		this.drawingarea1.Name = "drawingarea1";
		this.vbox1.Add(this.drawingarea1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.drawingarea1]));
		w3.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Subject ID  ");
		this.hbox3.Add(this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entrySUbjID = new global::Gtk.Entry();
		this.entrySUbjID.CanFocus = true;
		this.entrySUbjID.Name = "entrySUbjID";
		this.entrySUbjID.Text = global::Mono.Unix.Catalog.GetString("None");
		this.entrySUbjID.IsEditable = true;
		this.entrySUbjID.InvisibleChar = '●';
		this.hbox3.Add(this.entrySUbjID);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entrySUbjID]));
		w6.Position = 1;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Scan Name");
		this.hbox5.Add(this.label3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entryScanName = new global::Gtk.Entry();
		this.entryScanName.CanFocus = true;
		this.entryScanName.Name = "entryScanName";
		this.entryScanName.Text = global::Mono.Unix.Catalog.GetString("Scan-1");
		this.entryScanName.IsEditable = true;
		this.entryScanName.InvisibleChar = '●';
		this.hbox5.Add(this.entryScanName);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryScanName]));
		w9.Position = 1;
		this.vbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkAlignment5.Add(this.textview1);
		this.frame2.Add(this.GtkAlignment5);
		this.GtkLabel9 = new global::Gtk.Label();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString("Comments");
		this.GtkLabel9.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel9;
		this.vbox2.Add(this.frame2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
		w13.Position = 2;
		this.GtkAlignment.Add(this.vbox2);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>File Information</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel1;
		this.hbox1.Add(this.frame1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Data Shown");
		this.hbox8.Add(this.label7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label7]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.combobox5 = global::Gtk.ComboBox.NewText();
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("EMG"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("HbO2"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("HbR"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("HbT"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("StO2"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Optical Density 660nm"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Optical Density 850nm"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 660nm Det-1"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 660nm Det-2"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 660nm Det-3"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 660nm Det-4"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 850nm Det-1"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 850nm Det-2"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 850nm Det-3"));
		this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Raw 850nm Det-4"));
		this.combobox5.Name = "combobox5";
		this.combobox5.Active = 1;
		this.hbox8.Add(this.combobox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.combobox5]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox6.Add(this.hbox8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.entrywindowTime = new global::Gtk.Entry();
		this.entrywindowTime.CanFocus = true;
		this.entrywindowTime.Name = "entrywindowTime";
		this.entrywindowTime.Text = global::Mono.Unix.Catalog.GetString("60");
		this.entrywindowTime.IsEditable = true;
		this.entrywindowTime.InvisibleChar = '●';
		this.hbox10.Add(this.entrywindowTime);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entrywindowTime]));
		w20.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.checkbuttonWIndowTime = new global::Gtk.CheckButton();
		this.checkbuttonWIndowTime.CanFocus = true;
		this.checkbuttonWIndowTime.Name = "checkbuttonWIndowTime";
		this.checkbuttonWIndowTime.Label = global::Mono.Unix.Catalog.GetString("Window Data");
		this.checkbuttonWIndowTime.DrawIndicator = true;
		this.checkbuttonWIndowTime.UseUnderline = true;
		this.hbox10.Add(this.checkbuttonWIndowTime);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.checkbuttonWIndowTime]));
		w21.Position = 1;
		this.vbox6.Add(this.hbox10);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonMarkStim = new global::Gtk.Button();
		this.buttonMarkStim.CanFocus = true;
		this.buttonMarkStim.Name = "buttonMarkStim";
		this.buttonMarkStim.UseUnderline = true;
		this.buttonMarkStim.Label = global::Mono.Unix.Catalog.GetString("Mark Event");
		this.hbox7.Add(this.buttonMarkStim);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonMarkStim]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.labelEvents = new global::Gtk.Label();
		this.labelEvents.Name = "labelEvents";
		this.labelEvents.LabelProp = global::Mono.Unix.Catalog.GetString("No events");
		this.hbox7.Add(this.labelEvents);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.labelEvents]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.GtkAlignment2.Add(this.hbox7);
		this.frame5.Add(this.GtkAlignment2);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("Stimulus Events");
		this.GtkLabel4.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel4;
		this.vbox6.Add(this.frame5);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame5]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.GtkAlignment1.Add(this.vbox6);
		this.frame3.Add(this.GtkAlignment1);
		this.GtkLabel5 = new global::Gtk.Label();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Data Display</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel5;
		this.hbox1.Add(this.frame3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame3]));
		w30.Position = 1;
		w30.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button();
		this.buttonStart.Sensitive = false;
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.vbox7.Add(this.buttonStart);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.buttonStart]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar();
		this.progressbar1.Name = "progressbar1";
		this.vbox7.Add(this.progressbar1);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.progressbar1]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.frame9 = new global::Gtk.Frame();
		this.frame9.Name = "frame9";
		// Container child frame9.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("660nm");
		this.hbox12.Add(this.label9);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label9]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.spinbutton1 = new global::Gtk.SpinButton(0D, 255D, 5D);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10D;
		this.spinbutton1.ClimbRate = 10D;
		this.spinbutton1.Numeric = true;
		this.spinbutton1.Value = 255D;
		this.hbox12.Add(this.spinbutton1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.spinbutton1]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox8.Add(this.hbox12);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox12]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("850nm");
		this.hbox14.Add(this.label11);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label11]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.spinbutton3 = new global::Gtk.SpinButton(0D, 255D, 5D);
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10D;
		this.spinbutton3.ClimbRate = 5D;
		this.spinbutton3.Numeric = true;
		this.spinbutton3.Value = 255D;
		this.hbox14.Add(this.spinbutton3);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.spinbutton3]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox8.Add(this.hbox14);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox14]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		this.GtkAlignment4.Add(this.vbox8);
		this.frame9.Add(this.GtkAlignment4);
		this.GtkLabel7 = new global::Gtk.Label();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>LED Power</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame9.LabelWidget = this.GtkLabel7;
		this.vbox7.Add(this.frame9);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.frame9]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		this.GtkAlignment3.Add(this.vbox7);
		this.frame7.Add(this.GtkAlignment3);
		this.GtkLabel8 = new global::Gtk.Label();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Data Aquistion</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel8;
		this.hbox1.Add(this.frame7);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame7]));
		w44.Position = 2;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w45.Position = 3;
		w45.Expand = false;
		w45.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.StatusBarLabel1 = new global::Gtk.Label();
		this.StatusBarLabel1.Name = "StatusBarLabel1";
		this.StatusBarLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("No Device Connected");
		this.statusbar1.Add(this.StatusBarLabel1);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.StatusBarLabel1]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.statusbar1.Add(this.fixed1);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.fixed1]));
		w47.Position = 2;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.statusbar1.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.vseparator1]));
		w48.Position = 3;
		w48.Expand = false;
		w48.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.StatusBarLabel2 = new global::Gtk.Label();
		this.StatusBarLabel2.Name = "StatusBarLabel2";
		this.StatusBarLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Not Ready: Enter Subject ID First");
		this.statusbar1.Add(this.StatusBarLabel2);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.StatusBarLabel2]));
		w49.Position = 4;
		w49.Expand = false;
		w49.Fill = false;
		this.vbox1.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w50.Position = 4;
		w50.Expand = false;
		w50.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1007;
		this.DefaultHeight = 547;
		this.frame9.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.CloseProgram);
		this.ExitProgramAction.Activated += new global::System.EventHandler(this.ExitProgram);
		this.ConnectToDeviceAction.Activated += new global::System.EventHandler(this.ConnectDevice);
		this.entrySUbjID.Changed += new global::System.EventHandler(this.EnterSubjID);
		this.entryScanName.Changed += new global::System.EventHandler(this.EnterScanName);
		this.buttonMarkStim.Clicked += new global::System.EventHandler(this.MarkStimulus);
		this.buttonStart.Clicked += new global::System.EventHandler(this.ClickedStart);
	}
}
